### PR TITLE
Variable sized dist ut

### PR DESCRIPTION
**Pull request by tristan0x**
Hello @ibaned 
Thank you very much for your recent addition of function `create_dist_for_variable_sized`. I have troubles using it though. Could you please help me clarify what I am doing wrong (see second commit log for more information)?

Besides, when the test below will pass, I will add more tests, especially with several MPI ranks.

### CODE REVIEW

**Comment by ibaned** [comment]
I'm not 100% sure what the issue is here, but one problematic thing I can see is that the input `dist` used to help create the `vdist` doesn't satisfy the idea of "copies to owners", because it is reversing things. Changing line 27 to
```cpp
dist.set_dest_idxs(LOs({0, 1, 2, 3}), 4);
```
should help the `vdist` stuff, but it will change the expected answers

**Comment by tristan0x** [comment]
> I'm not 100% sure what the issue is here, but one problematic thing I can see is that the input `dist` used to help create the `vdist` doesn't satisfy the idea of "copies to owners", because it is reversing things. Changing line 27 to
> 
> ```c++
> dist.set_dest_idxs(LOs({0, 1, 2, 3}), 4);
> ```
> 
> should help the `vdist` stuff, but it will change the expected answers

Good morning @ibaned 
Thank you for your quick answer. I tried your suggestion but the same assert fails:

```
assertion a_data.size() == na * width failed at /goinfre/src/github.com/BlueBrain/omega_h/src/Omega_h_map.cpp +101

#0  0x00007ffff6ed0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6ed202a in __GI_abort () at abort.c:89
#2  0x00007ffff79a4420 in Omega_h::fail (format=format@entry=0x7ffff7b7fac0 "assertion %s failed at %s +%d\n")
    at /goinfre/src/github.com/BlueBrain/omega_h/src/Omega_h_fail.cpp:34
#3  0x00007ffff7a12842 in Omega_h::expand_into<int> (a_data=..., a2b=..., b_data=..., width=width@entry=1)
    at /goinfre/src/github.com/BlueBrain/omega_h/src/Omega_h_map.cpp:101
#4  0x00007ffff7a129a7 in Omega_h::expand<int> (a_data=..., a2b=..., width=width@entry=1) at /goinfre/src/github.com/BlueBrain/omega_h/src/Omega_h_map.cpp:117
#5  0x00007ffff798151a in Omega_h::Dist::exch<int> (this=this@entry=0x7fffffffcb70, data=..., width=width@entry=1)
    at /goinfre/src/github.com/BlueBrain/omega_h/src/Omega_h_dist.cpp:112
#6  0x00007ffff797d51f in Omega_h::create_dist_for_variable_sized (copies2owners=..., copies2data=...) at /goinfre/src/github.com/BlueBrain/omega_h/src/Omega_h_dist.cpp:231
#7  0x0000000000403f13 in test_one_rank (comm=std::shared_ptr<Omega_h::Comm> (use count 5, weak count 0) = {...})
    at /goinfre/src/github.com/BlueBrain/omega_h/src/mpi_tests.cpp:34
#8  0x0000000000402bef in main (argc=1, argv=0x7fffffffd1c8) at /goinfre/src/github.com/BlueBrain/omega_h/src/mpi_tests.cpp:280
```

**Comment by smelchio** [comment]
Good afternoon @ibaned 
Would you have time to have a look at the assert @tristan0x copied above when he tried your suggestion?
Thanks a lot and have a great WE!

**Comment by ibaned** [comment]
This latest commit looks good algorithmically! I would just say that for GPUs std::copy will not work, but that is less important in the short term. Let me know if you feel like it is fixed now, and I'll merge it and extend the std::copy as needed.

**Comment by tristan0x** [comment]
Thank you Dan.
To me, this branch Looks Good To Merge!

**Pull request merged**
