### PR TITLE
Fix compilation issues with clang-7 and clang-8

### PR DESCRIPTION
**Pull request by tristan0x**
Now compiles with `-Wno-return-std-move-in-c++11` on clang >=7
Otherwise compiler wants to `std::move` every returned local variable
to prevent a copy on old compilers.
Compilers have been doing copy elision for more than
a decade. I am afraid using `std::move` abusively prevent compiler using
copy elision.
What do you think @ibaned ? Should we `std::move` explicitly everywhere?

### CODE REVIEW

**Comment by ibaned** [comment]
By the way, why was Reader's default constructor deleted?

**Comment by tristan0x** [comment]
Because at least one of the member variables of the Reader class is a
reference. So default constructor is not applicable. I can remove it but it
will be removed implicitly by compiler anyway.

**Comment by tristan0x** [comment]
> Maybe we can do something like `OMEGA_H_NORETURN` which works around bad `noreturn` logic in compilers and do `OMEGA_H_MOVE_RETURN` to work around non-compliant compilers that fail to elide copies

This is a good idea. Have you already identified the compilers failing copy elision?

**Comment by ibaned** [comment]
We can start by defining this macro to never use `std::move` and see which compilers are still complaining ;)

**Pull request merged**
